### PR TITLE
test: ensure stacktrace test runs only on main repo

### LINKED ISSUE #85: Unit test fails when a fork is checked out.
when running the unit test for TestStacktrace on a fork on a local machine it fails.
```
=== RUN   TestStacktrace
=== PAUSE TestStacktrace
=== CONT  TestStacktrace
    stacktrace_test.go:52: 
        	Error Trace:	/home/sruehl/dev/workspace/sruehl/oops/stacktrace_test.go:52
        	Error:      	"/home/sruehl/dev/workspace/sruehl/oops/stacktrace_test.go" does not contain "github.com/samber/oops"
        	Test:       	TestStacktrace
        	Messages:   	frame file /home/sruehl/dev/workspace/sruehl/oops/stacktrace_test.go should contain github.com/samber/oops
```

Maybe we need to add a check there and if it detects it is not on the main project it just calls `t.Skip()`

### PR DESCRIPTION
**Pull request by sruehl**
fixes #85

### CODE REVIEW

File: stacktrace_test.go [hunk 1]
```diff
@@ -44,6 +44,9 @@ func TestStacktrace(t *testing.T) {
 
 	bi, ok := debug.ReadBuildInfo()
 	is.True(ok)
+	if strings.Contains(bi.Path, "github.com/samber/oops") {
+		t.Skip("This test is not meant to run on oops main repo")
```
Comment (samber) [inline stacktrace_test.go]:
```suggestion
		t.Skip("This test is meant to run on oops main repo")
```
